#!/usr/bin/env python
#coding:utf8
'''

nginx + uwsgi + flask


'''
-----------------------------------------------------------------	
requirement bag

flask
flask-sqlalchemy
flask-script
flask-migrate
uwsgi
#渲染模板
flask-bootstrap
#本地化日期和时间
flask-moment
- Flask-Login:管理已登录用户的用户会话。
- Werkzeug:计算密码散列值并进行核对。
- itsdangerous:生成并核对加密安全令牌。
- Flask-Mail:发送与认证相关的电子邮件。
- Flask-Bootstrap:HTML 模板。
- Flask-WTF:Web 表单。
-----------------------------------------------------------------
uwsgi startup method:

uwsgi config.ini  or
uwsgi --ini config.ini 
	uwsgi --xml
	      --json
	      --yam

-----------------------------------------------------------------
nginx:configration

server {
   listen 80;
   server_name domain_name;
   access_log /home/xuanwen/appserver/my_flask/logs/access.log;
   error_log /home/xuanwen/appserver/my_flask/logs/error.log;
   location / {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:5001;
        #uwsgi_pass unix:/tmp/uwsgi.sock;
        uwsgi_param UWSGI_PYHOME /home/xuanwen/appserver/my_flask/venv;
        uwsgi_param UWSGI_CHDIR  /home/xuanwen/appserver/my_flask;
        uwsgi_param UWSGI_SCRIPT manage:app;
   }
}

-----------------------------------------------------------------
#查看安装的依赖包机版本
pip freeze > requirements.txt
#安装依赖包
pip install -r requirements.txt

-----------------------------------------------------------------

